import { ChineseCharacter } from '../types';

export const CHINESE_CHARACTERS: ChineseCharacter[] = [
  {
    character: '一',
    pinyin: 'yī',
    hanViet: 'nhất',
    meaning: 'một',
    radical: '一 (yī) – bộ Nhất',
    characterType: 'Chỉ sự',
  },
  {
    character: '八',
    pinyin: 'bā',
    hanViet: 'bát',
    meaning: 'tám',
    radical: '八 (bā) – bộ Bát',
    characterType: 'Chỉ sự',
  },
  {
    character: '五',
    pinyin: 'wǔ',
    hanViet: 'ngũ',
    meaning: 'năm',
    radical: '二 (èr) – bộ Nhị',
    characterType: 'Chỉ sự',
  },
  {
    character: '不',
    pinyin: 'bù',
    hanViet: 'bất',
    meaning: 'không',
    radical: '一 (yī) – bộ Nhất',
    characterType: 'Giả tá',
  },
  {
    character: '大',
    pinyin: 'dà',
    hanViet: 'đại',
    meaning: 'to, lớn',
    radical: '大 (dà) – bộ Đại',
    characterType: 'Tượng hình',
  },
  {
    character: '口',
    pinyin: 'kǒu',
    hanViet: 'khẩu',
    meaning: 'miệng, nhân khẩu',
    radical: '口 (kǒu) – bộ Khẩu',
    characterType: 'Tượng hình',
  },
  {
    character: '白',
    pinyin: 'bái',
    hanViet: 'bạch',
    meaning: 'trắng',
    radical: '白 (bái) – bộ Bạch',
    characterType: 'Tượng hình',
  },
  {
    character: '女',
    pinyin: 'nǚ',
    hanViet: 'nữ',
    meaning: 'nữ, phụ nữ',
    radical: '女 (nǚ) – bộ Nữ',
    characterType: 'Tượng hình',
  },
  {
    character: '你',
    pinyin: 'nǐ',
    hanViet: 'nhĩ',
    meaning: 'bạn, anh, chị',
    radical: '亻 (rén) – bộ Nhân đứng',
    characterType: 'Hình thanh',
  },
  {
    character: '好',
    pinyin: 'hǎo',
    hanViet: 'hảo',
    meaning: 'tốt, đẹp',
    radical: '女 (nǚ) – bộ Nữ',
    characterType: 'Hội ý',
  },
  {
    character: '马',
    pinyin: 'mǎ',
    hanViet: 'mã',
    meaning: 'ngựa',
    radical: '马 (mǎ) – bộ Mã',
    characterType: 'Tượng hình',
  },
  {
    character: '太',
    pinyin: 'tài',
    hanViet: 'thái',
    meaning: 'quá, cực kỳ',
    radical: '大 (dà) – bộ Đại',
    characterType: 'Chỉ sự',
  },
  {
    character: '汉',
    pinyin: 'hàn',
    hanViet: 'hán',
    meaning: 'nhà Hán, người Hán',
    radical: '氵 (shuǐ) – bộ Thủy (ba chấm nước)',
    characterType: 'Hình thanh',
  },
  {
    character: '语',
    pinyin: 'yǔ',
    hanViet: 'ngữ',
    meaning: 'ngôn ngữ, lời nói',
    radical: '讠 (yán) – bộ Ngôn',
    characterType: 'Hình thanh',
  },
  {
    character: '吗',
    pinyin: 'ma',
    hanViet: 'ma',
    meaning: 'trợ từ nghi vấn',
    radical: '口 (kǒu) – bộ Khẩu',
    characterType: 'Hình thanh',
  },
  {
    character: '妈',
    pinyin: 'mā',
    hanViet: 'ma',
    meaning: 'mẹ',
    radical: '女 (nǚ) – bộ Nữ',
    characterType: 'Hình thanh',
  },
  {
    character: '爸',
    pinyin: 'bà',
    hanViet: 'ba',
    meaning: 'ba, bố',
    radical: '父 (fù) – bộ Phụ',
    characterType: 'Hình thanh',
  },
  {
    character: '很',
    pinyin: 'hěn',
    hanViet: 'ngận',
    meaning: 'rất',
    radical: '彳 (chì) – bộ Sách (bước chân trái)',
    characterType: 'Hình thanh',
  },
  {
    character: '忙',
    pinyin: 'máng',
    hanViet: 'mang',
    meaning: 'bận',
    radical: '忄 (xīn) – bộ Tâm đứng',
    characterType: 'Hình thanh',
  },
  {
    character: '他',
    pinyin: 'tā',
    hanViet: 'tha',
    meaning: 'anh ấy, ông ấy, họ',
    radical: '亻 (rén) – bộ Nhân đứng',
    characterType: 'Hình thanh',
  },
  {
    character: '她',
    pinyin: 'tā',
    hanViet: 'tha',
    meaning: 'cô ấy, chị ấy',
    radical: '女 (nǚ) – bộ Nữ',
    characterType: 'Hình thanh',
  },
  {
    character: '难',
    pinyin: 'nán',
    hanViet: 'nan',
    meaning: 'khó',
    radical: '隹 (zhuī) – bộ Chuy',
    characterType: 'Hình thanh',
  },
  {
    character: '六',
    pinyin: 'liù',
    hanViet: 'lục',
    meaning: 'sáu',
    radical: '八 (bā) – bộ Bát',
    characterType: 'Tượng hình',
  },
  {
    character: '七',
    pinyin: 'qī',
    hanViet: 'thất',
    meaning: 'bảy',
    radical: '一 (yī) – bộ Nhất',
    characterType: 'Chỉ sự',
  },
  {
    character: '九',
    pinyin: 'jiǔ',
    hanViet: 'cửu',
    meaning: 'chín',
    radical: '乙 (yǐ) – bộ Ất',
    characterType: 'Tượng hình',
  },
  {
    character: '学',
    pinyin: 'xué',
    hanViet: 'học',
    meaning: 'học',
    radical: '子 (zǐ) – bộ Tử',
    characterType: 'Hội ý',
  },
  {
    character: '去',
    pinyin: 'qù',
    hanViet: 'khứ',
    meaning: 'đi',
    radical: '厶 (sī) – bộ Khư',
    characterType: 'Hội ý',
  },
  {
    character: '北',
    pinyin: 'běi',
    hanViet: 'bắc',
    meaning: 'phía bắc',
    radical: '匕 (bǐ) – bộ Chủy',
    characterType: 'Hội ý',
  },
  {
    character: '京',
    pinyin: 'jīng',
    hanViet: 'kinh',
    meaning: 'kinh đô',
    radical: '亠 (tóu) – bộ Đầu',
    characterType: 'Tượng hình',
  },
  {
    character: '对',
    pinyin: 'duì',
    hanViet: 'đối',
    meaning: 'đúng, đối với',
    radical: '寸 (cùn) – bộ Thốn',
    characterType: 'Hội ý',
  },
  {
    character: '明',
    pinyin: 'míng',
    hanViet: 'minh',
    meaning: 'sáng, rõ',
    radical: '日 (rì) – bộ Nhật',
    characterType: 'Hội ý',
  },
  {
    character: '天',
    pinyin: 'tiān',
    hanViet: 'thiên',
    meaning: 'trời, ngày',
    radical: '大 (dà) – bộ Đại',
    characterType: 'Chỉ sự',
  },
  {
    character: '见',
    pinyin: 'jiàn',
    hanViet: 'kiến',
    meaning: 'thấy, gặp',
    radical: '见 (jiàn) – bộ Kiến',
    characterType: 'Tượng hình',
  },
  {
    character: '银',
    pinyin: 'yín',
    hanViet: 'ngân',
    meaning: 'bạc, ngân hàng',
    radical: '钅 (jīn) – bộ Kim',
    characterType: 'Hình thanh',
  },
  {
    character: '行',
    pinyin: 'xíng',
    hanViet: 'hành',
    meaning: 'đi, được, OK',
    radical: '行 (xíng) – bộ Hành',
    characterType: 'Tượng hình',
  },
  {
    character: '二',
    pinyin: 'èr',
    hanViet: 'nhị',
    meaning: 'hai',
    radical: '二 (èr) – bộ Nhị',
    characterType: 'Chỉ sự',
  },
  {
    character: '三',
    pinyin: 'sān',
    hanViet: 'tam',
    meaning: 'ba',
    radical: '一 (yī) – bộ Nhất',
    characterType: 'Chỉ sự',
  },
  {
    character: '四',
    pinyin: 'sì',
    hanViet: 'tứ',
    meaning: 'bốn',
    radical: '囗 (wéi) – bộ Vi',
    characterType: 'Chỉ sự',
  },
  {
    character: '今',
    pinyin: 'jīn',
    hanViet: 'kim',
    meaning: 'nay, hiện tại, bây giờ',
    radical: '人 (rén) – bộ Nhân',
    characterType: 'Chỉ sự',
  },
  {
    character: '我',
    pinyin: 'wǒ',
    hanViet: 'ngã',
    meaning: 'tôi',
    radical: '戈 (gē) – bộ Qua',
    characterType: 'Giả tá',
  },
  {
    character: '关',
    pinyin: 'guān',
    hanViet: 'quan',
    meaning: 'đóng, tắt, cửa ải, liên quan',
    radical: '丷 (bā) – bộ Bát',
    characterType: 'Hội ý',
  },
  {
    character: '星',
    pinyin: 'xīng',
    hanViet: 'tinh',
    meaning: 'ngôi sao',
    radical: '日 (rì) – bộ Nhật',
    characterType: 'Hình thanh',
  },
  {
    character: '期',
    pinyin: 'qī',
    hanViet: 'kỳ',
    meaning: 'kỳ, thời hạn, giai đoạn',
    radical: '月 (yuè) – bộ Nguyệt',
    characterType: 'Hình thanh',
  },
  {
    character: '几',
    pinyin: 'jǐ',
    hanViet: 'kỷ',
    meaning: 'mấy, bao nhiêu',
    radical: '几 (jǐ) – bộ Kỷ',
    characterType: 'Tượng hình',
  },
  {
    character: '上',
    pinyin: 'shàng',
    hanViet: 'thượng',
    meaning: 'trên, lên, phía trên',
    radical: '一 (yī) – bộ Nhất',
    characterType: 'Chỉ sự',
  },
  {
    character: '下',
    pinyin: 'xià',
    hanViet: 'hạ',
    meaning: 'dưới, xuống, phía dưới',
    radical: '一 (yī) – bộ Nhất',
    characterType: 'Chỉ sự',
  },
  {
    character: '日',
    pinyin: 'rì',
    hanViet: 'nhật',
    meaning: 'mặt trời, ngày',
    radical: '日 (rì) – bộ Nhật',
    characterType: 'Tượng hình',
  },
  {
    character: '月',
    pinyin: 'yuè',
    hanViet: 'nguyệt',
    meaning: 'mặt trăng, tháng',
    radical: '月 (yuè) – bộ Nguyệt',
    characterType: 'Tượng hình',
  },
  {
    character: '生',
    pinyin: 'shēng',
    hanViet: 'sinh',
    meaning: 'sinh, sống, sinh ra',
    radical: '生 (shēng) – bộ Sinh',
    characterType: 'Chỉ sự',
  },
  {
    character: '了',
    pinyin: 'le',
    hanViet: 'liễu',
    meaning: 'trợ từ chỉ sự hoàn thành; xong, rồi',
    radical: '乙 (yǐ) – bộ Ất',
    characterType: 'Giả tá',
  },
  {
    character: '木',
    pinyin: 'mù',
    hanViet: 'mộc',
    meaning: 'cây, gỗ',
    radical: '木 (mù) – bộ Mộc',
    characterType: 'Tượng hình',
  },
  {
    character: '休',
    pinyin: 'xiū',
    hanViet: 'hưu',
    meaning: 'nghỉ ngơi',
    radical: '亻 (rén) – bộ Nhân đứng',
    characterType: 'Hội ý',
  },
  {
    character: '亡',
    pinyin: 'wáng',
    hanViet: 'vong',
    meaning: 'mất, chết, vong',
    radical: '亠 (tóu) – bộ Đầu',
    characterType: 'Chỉ sự',
  },
  {
    character: '也',
    pinyin: 'yě',
    hanViet: 'dã',
    meaning: 'cũng',
    radical: '乙 (yǐ) – bộ Ất',
    characterType: 'Giả tá',
  },
  {
    character: '又',
    pinyin: 'yòu',
    hanViet: 'hựu',
    meaning: 'lại, nữa',
    radical: '又 (yòu) – bộ Hựu',
    characterType: 'Tượng hình',
  },
  {
    character: '子',
    pinyin: 'zǐ',
    hanViet: 'tử',
    meaning: 'con, con cái, đứa trẻ',
    radical: '子 (zǐ) – bộ Tử',
    characterType: 'Tượng hình',
  },
  {
    character: '小',
    pinyin: 'xiǎo',
    hanViet: 'tiểu',
    meaning: 'nhỏ, bé',
    radical: '小 (xiǎo) – bộ Tiểu',
    characterType: 'Chỉ sự',
  },
];
