import { ChineseCharacter } from '../types';

export const CHARS_PER_LESSON = 9;

/**
 * Raw character data in curriculum order.
 * Lesson numbers are auto-computed: every 9 characters = 1 lesson.
 * To add new characters, just append them to this array.
 */
type RawCharacter = Omit<ChineseCharacter, 'lesson'>;

const RAW_CHARACTERS: RawCharacter[] = [
  // ─── Your curriculum order ───
  // Bài 1 (index 0–8)
  { character: '一', pinyin: 'yī', hanViet: 'nhất', meaning: 'một' },
  { character: '八', pinyin: 'bā', hanViet: 'bát', meaning: 'tám' },
  { character: '五', pinyin: 'wǔ', hanViet: 'ngũ', meaning: 'năm' },
  { character: '不', pinyin: 'bù', hanViet: 'bất', meaning: 'không' },
  { character: '大', pinyin: 'dà', hanViet: 'đại', meaning: 'to, lớn' },
  { character: '口', pinyin: 'kǒu', hanViet: 'khẩu', meaning: 'miệng, nhân khẩu' },
  { character: '白', pinyin: 'bái', hanViet: 'bạch', meaning: 'trắng' },
  { character: '女', pinyin: 'nǚ', hanViet: 'nữ', meaning: 'nữ, phụ nữ' },
  { character: '你', pinyin: 'nǐ', hanViet: 'nhĩ', meaning: 'bạn, anh, chị' },
  // Bài 2 (index 9–17)
  { character: '好', pinyin: 'hǎo', hanViet: 'hảo', meaning: 'tốt, đẹp' },
  { character: '马', pinyin: 'mǎ', hanViet: 'mã', meaning: 'ngựa' },
  { character: '太', pinyin: 'tài', hanViet: 'thái', meaning: 'quá, cực kỳ' },
  { character: '汉', pinyin: 'hàn', hanViet: 'hán', meaning: 'nhà Hán, người Hán' },
  { character: '语', pinyin: 'yǔ', hanViet: 'ngữ', meaning: 'ngôn ngữ, lời nói' },
  { character: '吗', pinyin: 'ma', hanViet: 'ma', meaning: 'trợ từ nghi vấn' },
  { character: '妈', pinyin: 'mā', hanViet: 'ma', meaning: 'mẹ' },
  { character: '爸', pinyin: 'bà', hanViet: 'ba', meaning: 'ba, bố' },
  { character: '很', pinyin: 'hěn', hanViet: 'ngận', meaning: 'rất' },
  // Bài 3 (index 18–26)
  { character: '忙', pinyin: 'máng', hanViet: 'mang', meaning: 'bận' },
  { character: '他', pinyin: 'tā', hanViet: 'tha', meaning: 'anh ấy, ông ấy, họ' },
  { character: '她', pinyin: 'tā', hanViet: 'tha', meaning: 'cô ấy, chị ấy' },
  { character: '难', pinyin: 'nán', hanViet: 'nan', meaning: 'khó' },
  { character: '六', pinyin: 'liù', hanViet: 'lục', meaning: 'sáu' },
  { character: '七', pinyin: 'qī', hanViet: 'thất', meaning: 'bảy' },
  { character: '九', pinyin: 'jiǔ', hanViet: 'cửu', meaning: 'chín' },
  { character: '学', pinyin: 'xué', hanViet: 'học', meaning: 'học' },
  { character: '去', pinyin: 'qù', hanViet: 'khứ', meaning: 'đi' },
  // Bài 4 (index 27–35)
  { character: '北', pinyin: 'běi', hanViet: 'bắc', meaning: 'phía bắc' },
  { character: '京', pinyin: 'jīng', hanViet: 'kinh', meaning: 'kinh đô' },
  { character: '对', pinyin: 'duì', hanViet: 'đối', meaning: 'đúng, đối với' },
  { character: '明', pinyin: 'míng', hanViet: 'minh', meaning: 'sáng, rõ' },
  { character: '天', pinyin: 'tiān', hanViet: 'thiên', meaning: 'trời, ngày' },
  { character: '见', pinyin: 'jiàn', hanViet: 'kiến', meaning: 'thấy, gặp' },
  { character: '银', pinyin: 'yín', hanViet: 'ngân', meaning: 'bạc, ngân hàng' },
  { character: '行', pinyin: 'xíng/háng', hanViet: 'hành', meaning: 'đi, được, OK, hàng, tiệm' },
  { character: '二', pinyin: 'èr', hanViet: 'nhị', meaning: 'hai' },
  // Bài 5 (index 36–44)
  { character: '三', pinyin: 'sān', hanViet: 'tam', meaning: 'ba' },
  { character: '四', pinyin: 'sì', hanViet: 'tứ', meaning: 'bốn' },
  { character: '今', pinyin: 'jīn', hanViet: 'kim', meaning: 'nay, hiện tại, bây giờ' },
  { character: '关', pinyin: 'guān', hanViet: 'quan', meaning: 'đóng, tắt, cửa ải, liên quan' },
  { character: '星', pinyin: 'xīng', hanViet: 'tinh', meaning: 'ngôi sao' },
  { character: '期', pinyin: 'qī', hanViet: 'kỳ', meaning: 'kỳ, thời hạn, giai đoạn' },
  { character: '几', pinyin: 'jǐ', hanViet: 'kỷ', meaning: 'mấy, bao nhiêu' },
  { character: '我', pinyin: 'wǒ', hanViet: 'ngã', meaning: 'tôi' },
  { character: '回', pinyin: 'huí', hanViet: 'hồi', meaning: 'quay lại, trở về' },
  // Bài 6 (index 45–53)
  { character: '校', pinyin: 'xiào', hanViet: 'hiệu', meaning: 'trường, trường học' },
  { character: '那', pinyin: 'nà, nèi', hanViet: 'na', meaning: 'kia, đó' },
  { character: '哪', pinyin: 'nǎ, něi', hanViet: 'na', meaning: 'nào, đâu, ở đâu' },
  { character: '十', pinyin: 'shí', hanViet: 'thập', meaning: 'mười' },
  { character: '工', pinyin: 'gōng', hanViet: 'công', meaning: 'công, việc, công việc, thợ' },
  { character: '作', pinyin: 'zuò', hanViet: 'tác', meaning: 'làm, tạo ra, sáng tạo, làm việc' },
  { character: '日', pinyin: 'rì', hanViet: 'nhật', meaning: 'mặt trời, ngày' },
  { character: '是', pinyin: 'shì', hanViet: 'thị', meaning: 'là, đúng, phải' },
  { character: '这', pinyin: 'zhè', hanViet: 'giá', meaning: 'đây, cái này' },
  // Bài 7 (index 54–62)
  { character: '进', pinyin: 'jìn', hanViet: 'tiến', meaning: 'vào, tiến vào, tiến lên' },
  { character: '老', pinyin: 'lǎo', hanViet: 'lão', meaning: 'già, lớn tuổi, cũ, lâu năm' },
  { character: '师', pinyin: 'shī', hanViet: 'sư', meaning: 'thầy, giáo viên, sư phụ' },
  { character: '身', pinyin: 'shēn', hanViet: 'thân', meaning: 'thân, thân thể, cơ thể' },
  { character: '体', pinyin: 'tǐ', hanViet: 'thể', meaning: 'thân thể, cơ thể' },
  { character: '谢', pinyin: 'xiè', hanViet: 'tạ', meaning: 'cảm ơn, xin lỗi, từ chối, tàn' },
  { character: '人', pinyin: 'rén', hanViet: 'nhân', meaning: 'người' },
  { character: '问', pinyin: 'wèn', hanViet: 'vấn', meaning: 'hỏi' },
  { character: '叫', pinyin: 'jiào', hanViet: 'khiếu', meaning: 'gọi, kêu' },
  // Bài 8 (index 63–71)
  { character: '名', pinyin: 'míng', hanViet: 'danh', meaning: 'tên, tên gọi' },
  { character: '字', pinyin: 'zì', hanViet: 'tự', meaning: 'chữ, chữ viết, văn tự' },
  { character: '国', pinyin: 'guó', hanViet: 'quốc', meaning: 'nước, quốc gia' },
  { character: '中', pinyin: 'zhōng', hanViet: 'trung', meaning: 'ở giữa, trung tâm' },
  { character: '文', pinyin: 'wén', hanViet: 'văn', meaning: 'văn, chữ viết, văn tự, hoa văn' },
  { character: '习', pinyin: 'xí', hanViet: 'tập', meaning: 'luyện tập, học' },
  { character: '发', pinyin: 'fā', hanViet: 'phát', meaning: 'phát ra, phát triển, phát sinh' },
  { character: '音', pinyin: 'yīn', hanViet: 'âm', meaning: 'âm thanh, tiếng' },
  { character: '朋', pinyin: 'péng', hanViet: 'bằng', meaning: 'bạn bè' },
  // Bài 9 (index 72–80)
  { character: '友', pinyin: 'yǒu', hanViet: 'hữu', meaning: 'bạn, bạn bè' },
  { character: '书', pinyin: 'shū', hanViet: 'thư', meaning: 'sách, viết, ghi chép' },
  { character: '个', pinyin: 'gè', hanViet: 'cá', meaning: 'lượng từ (cái, chiếc, con)' },
  { character: '午', pinyin: 'wǔ', hanViet: 'ngọ', meaning: 'trưa, buổi trưa' },
  { character: '子', pinyin: 'zǐ', hanViet: 'tử', meaning: 'con, con cái, đứa trẻ' },
  { character: '头', pinyin: 'tóu', hanViet: 'đầu', meaning: 'đầu, cái đầu' },
  { character: '要', pinyin: 'yào', hanViet: 'yếu', meaning: 'muốn, cần' },
  { character: '吃', pinyin: 'chī', hanViet: 'ngật', meaning: 'ăn' },
  { character: '饭', pinyin: 'fàn', hanViet: 'phạn', meaning: 'cơm' },
  // Bài 10 (index 81–89)
  { character: '些', pinyin: 'xiē', hanViet: 'ta', meaning: 'một ít, vài, một số' },
  { character: '包', pinyin: 'bāo', hanViet: 'bao', meaning: 'gói, bao, bọc, chứa đựng' },
  { character: '面', pinyin: 'miàn', hanViet: 'diện', meaning: 'mặt, bề mặt, mì' },
  { character: '条', pinyin: 'tiáo', hanViet: 'điều', meaning: 'sợi, vật dài; điều, khoản; lượng từ' },
  { character: '喝', pinyin: 'hē', hanViet: 'hạt', meaning: 'uống' },
  { character: '们', pinyin: 'men', hanViet: 'môn', meaning: 'trợ từ số nhiều dùng sau đại từ hoặc từ chỉ người' },
  { character: '小', pinyin: 'xiǎo', hanViet: 'tiểu', meaning: 'nhỏ, bé' },
  { character: '月', pinyin: 'yuè', hanViet: 'nguyệt', meaning: 'mặt trăng, tháng' },
  { character: '上', pinyin: 'shàng', hanViet: 'thượng', meaning: 'trên, lên, phía trên' },
  // Bài 11 (index 90–98)
  { character: '下', pinyin: 'xià', hanViet: 'hạ', meaning: 'dưới, xuống, phía dưới' },
  { character: '生', pinyin: 'shēng', hanViet: 'sinh', meaning: 'sinh, sống, sinh ra' },
  { character: '昨', pinyin: 'zuó', hanViet: 'tạc', meaning: 'hôm qua' },
  { character: '门', pinyin: 'mén', hanViet: 'môn', meaning: 'cửa' },
  { character: '米', pinyin: 'mǐ', hanViet: 'mễ', meaning: 'gạo, mét' },
  { character: '也', pinyin: 'yě', hanViet: 'dã', meaning: 'cũng' },
  { character: '又', pinyin: 'yòu', hanViet: 'hựu', meaning: 'lại, nữa' },
  { character: '了', pinyin: 'le', hanViet: 'liễu', meaning: 'trợ từ chỉ sự hoàn thành; xong, rồi' },
  { character: '木', pinyin: 'mù', hanViet: 'mộc', meaning: 'cây, gỗ' },
  // Bài 12 (index 99–107)
  { character: '休', pinyin: 'xiū', hanViet: 'hưu', meaning: 'nghỉ ngơi' },
  { character: '亡', pinyin: 'wáng', hanViet: 'vong', meaning: 'mất, chết, vong' },
  { character: '酒', pinyin: 'jiǔ', hanViet: 'tửu', meaning: 'rượu' },
  { character: '元', pinyin: 'yuán', hanViet: 'nguyên', meaning: 'đầu, đầu tiên, bắt đầu, đồng (tiền)' },
  { character: '毛', pinyin: 'máo', hanViet: 'mao', meaning: 'lông, hào' },
  { character: '分', pinyin: 'fēn', hanViet: 'phân', meaning: 'chia ra, phân chia' },
  { character: '斤', pinyin: 'jīn', hanViet: 'cân', meaning: 'cân, đơn vị cân nặng' },
  { character: '多', pinyin: 'duō', hanViet: 'đa', meaning: 'nhiều' },
  { character: '少', pinyin: 'shǎo', hanViet: 'thiểu', meaning: 'ít, thiếu, trẻ' },
  // Bài 13 (index 108–116)
  { character: '还', pinyin: 'hái, huán', hanViet: 'hoàn', meaning: 'còn, vẫn, lại; trả, quay về' },
  { character: '买', pinyin: 'mǎi', hanViet: 'mãi', meaning: 'mua' },
  { character: '卖', pinyin: 'mài', hanViet: 'mại', meaning: 'bán' },
  { character: '吧', pinyin: 'ba', hanViet: 'ba', meaning: 'trợ từ ngữ khí cuối câu, biểu thị đề nghị, phỏng đoán hoặc làm nhẹ giọng' },
  { character: '两', pinyin: 'liǎng', hanViet: 'lưỡng', meaning: 'hai, đôi, cặp, hai bên' },
  { character: '别', pinyin: 'bié', hanViet: 'biệt', meaning: 'khác, đừng, tách ra, từ biệt' },
  { character: '给', pinyin: 'gěi', hanViet: 'cấp', meaning: 'cho, cấp cho, cung cấp' },
  { character: '找', pinyin: 'zhǎo', hanViet: 'trảo', meaning: 'tìm, trả lại tiền thừa' },
  { character: '百', pinyin: 'bǎi', hanViet: 'bách', meaning: 'một trăm' },
  { character: '千', pinyin: 'qiān', hanViet: 'thiên', meaning: 'một nghìn' },
  { character: '万', pinyin: 'wàn', hanViet: 'vạn', meaning: 'mười nghìn' },
  { character: '美', pinyin: 'měi', hanViet: 'mỹ', meaning: 'đẹp, đẹp đẽ' },
  { character: '民', pinyin: 'mín', hanViet: 'dân', meaning: 'dân, người dân, dân thường' },
  { character: '先', pinyin: 'xiān', hanViet: 'tiên', meaning: 'trước, trước tiên, ưu tiên' },
  { character: '客', pinyin: 'kè', hanViet: 'khách', meaning: 'khách, người đến từ bên ngoài' },
  { character: '气', pinyin: 'qì', hanViet: 'khí', meaning: 'hơi, khí, không khí' },
  { character: '住', pinyin: 'zhù', hanViet: 'trú', meaning: 'ở, cư trú, dừng lại' },
  { character: '办', pinyin: 'bàn', hanViet: 'biện', meaning: 'làm, xử lý, giải quyết công việc' },
  { character: '公', pinyin: 'gōng', hanViet: 'công', meaning: 'của chung, công cộng' },
  { character: '室', pinyin: 'shì', hanViet: 'thất', meaning: 'phòng' },
  { character: '在', pinyin: 'zài', hanViet: 'tại', meaning: 'ở, đang' },
  { character: '家', pinyin: 'jiā', hanViet: 'gia', meaning: 'nhà' },
  { character: '呢', pinyin: 'ne', hanViet: 'ni', meaning: 'trợ từ nghi vấn' },
  { character: '知', pinyin: 'zhī', hanViet: 'tri', meaning: 'biết' },
  { character: '道', pinyin: 'dào', hanViet: 'đạo', meaning: 'đường, biết' },
  { character: '电', pinyin: 'diàn', hanViet: 'điện', meaning: 'điện' },
  { character: '话', pinyin: 'huà', hanViet: 'thoại', meaning: 'lời nói, thoại' },
  { character: '号', pinyin: 'hào', hanViet: 'hiệu', meaning: 'số, ký hiệu' },
  { character: '手', pinyin: 'shǒu', hanViet: 'thủ', meaning: 'tay' },
  { character: '机', pinyin: 'jī', hanViet: 'cơ', meaning: 'máy' },
  { character: '介', pinyin: 'jiè', hanViet: 'giới', meaning: 'giới thiệu, ở giữa' },
  { character: '绍', pinyin: 'shào', hanViet: 'thiệu', meaning: 'nối tiếp, giới thiệu' },
  { character: '留', pinyin: 'liú', hanViet: 'lưu', meaning: 'giữ lại, ở lại' },
  { character: '和', pinyin: 'hé', hanViet: 'hòa', meaning: 'và, hòa' },
  { character: '长', pinyin: 'cháng', hanViet: 'trường', meaning: 'dài' },
  { character: '起', pinyin: 'qǐ', hanViet: 'khởi', meaning: 'bắt đầu, đứng dậy' },
  { character: '没', pinyin: 'méi', hanViet: 'một', meaning: 'không, chưa' },
  { character: '系', pinyin: 'xì', hanViet: 'hệ', meaning: 'hệ, liên hệ' },
  { character: '言', pinyin: 'yán', hanViet: 'ngôn', meaning: 'lời nói' },
  { character: '怎', pinyin: 'zěn', hanViet: 'chẩm', meaning: 'thế nào, sao' },
  { character: '么', pinyin: 'me', hanViet: 'ma', meaning: 'trợ từ' },
  { character: '样', pinyin: 'yàng', hanViet: 'dạng', meaning: 'kiểu, dáng vẻ' },
  { character: '法', pinyin: 'fǎ', hanViet: 'pháp', meaning: 'phương pháp, pháp luật' },
  { character: '同', pinyin: 'tóng', hanViet: 'đồng', meaning: 'cùng, giống' },
  { character: '比', pinyin: 'bǐ', hanViet: 'tỷ', meaning: 'so sánh' },
  { character: '觉', pinyin: 'jué', hanViet: 'giác', meaning: 'cảm thấy, nhận biết' },
  { character: '得', pinyin: 'dé', hanViet: 'đắc', meaning: 'được' },
  { character: '听', pinyin: 'tīng', hanViet: 'thính', meaning: 'nghe' },
  { character: '说', pinyin: 'shuō', hanViet: 'thuyết', meaning: 'nói' },
  { character: '读', pinyin: 'dú', hanViet: 'độc', meaning: 'đọc' },
  { character: '写', pinyin: 'xiě', hanViet: 'tả', meaning: 'viết' },
  { character: '有', pinyin: 'yǒu', hanViet: 'hữu', meaning: 'có' },
  { character: '词', pinyin: 'cí', hanViet: 'từ', meaning: 'từ, từ vựng' },
  { character: '雨', pinyin: 'yǔ', hanViet: 'vũ', meaning: 'mưa' },
  { character: '金', pinyin: 'jīn', hanViet: 'kim', meaning: 'vàng, kim loại' },
  { character: '衣', pinyin: 'yī', hanViet: 'y', meaning: 'quần áo' },
  { character: '服', pinyin: 'fú', hanViet: 'phục', meaning: 'quần áo, phục' },
  { character: '东', pinyin: 'dōng', hanViet: 'đông', meaning: 'phía đông' },
  { character: '西', pinyin: 'xī', hanViet: 'tây', meaning: 'phía tây' },
  { character: '新', pinyin: 'xīn', hanViet: 'tân', meaning: 'mới' },
  { character: '旧', pinyin: 'jiù', hanViet: 'cựu', meaning: 'cũ' },
  { character: '团', pinyin: 'tuán', hanViet: 'đoàn', meaning: 'nhóm, đoàn' },
  { character: '件', pinyin: 'jiàn', hanViet: 'kiện', meaning: 'vật, chiếc, kiện' },
  { character: '水', pinyin: 'shuǐ', hanViet: 'thủy', meaning: 'nước' },
  { character: '红', pinyin: 'hóng', hanViet: 'hồng', meaning: 'màu đỏ' },
  { character: '笔', pinyin: 'bǐ', hanViet: 'bút', meaning: 'bút' },
  { character: '刚', pinyin: 'gāng', hanViet: 'cương', meaning: 'vừa mới' },
  { character: '近', pinyin: 'jìn', hanViet: 'cận', meaning: 'gần' },
  { character: '欢', pinyin: 'huān', hanViet: 'hoan', meaning: 'vui, thích' },
  { character: '迎', pinyin: 'yíng', hanViet: 'nghênh', meaning: 'đón, nghênh đón' },
  { character: '开', pinyin: 'kāi', hanViet: 'khai', meaning: 'mở' },
  { character: '点', pinyin: 'diǎn', hanViet: 'điểm', meaning: 'điểm, giờ' },
  { character: '儿', pinyin: 'ér', hanViet: 'nhi', meaning: 'con, trẻ nhỏ' },
  { character: '自', pinyin: 'zì', hanViet: 'tự', meaning: 'tự, bản thân' },
  { character: '车', pinyin: 'chē', hanViet: 'xa', meaning: 'xe' },
  { character: '色', pinyin: 'sè', hanViet: 'sắc', meaning: 'màu sắc' },
  { character: '蓝', pinyin: 'lán', hanViet: 'lam', meaning: 'màu xanh lam' },
  { character: '只', pinyin: 'zhǐ', hanViet: 'chỉ', meaning: 'chỉ, chỉ có' },
  { character: '夫', pinyin: 'fū', hanViet: 'phu', meaning: 'chồng, đàn ông' },
  { character: '片', pinyin: 'piàn', hanViet: 'phiến', meaning: 'miếng, lát, mảnh' },
  { character: '全', pinyin: 'quán', hanViet: 'toàn', meaning: 'toàn bộ' },
  { character: '医', pinyin: 'yī', hanViet: 'y', meaning: 'y học, bác sĩ' },
  { character: '院', pinyin: 'yuàn', hanViet: 'viện', meaning: 'viện, sân' },
  { character: '姐', pinyin: 'jiě', hanViet: 'tả', meaning: 'chị gái' },
  { character: '哥', pinyin: 'gē', hanViet: 'ca', meaning: 'anh trai' },
  { character: '弟', pinyin: 'dì', hanViet: 'đệ', meaning: 'em trai' },
  { character: '都', pinyin: 'dōu', hanViet: 'đô', meaning: 'đều' },
  { character: '理', pinyin: 'lǐ', hanViet: 'lí', meaning: 'lý lẽ, xử lý' },
  { character: '安', pinyin: 'ān', hanViet: 'an', meaning: 'yên, an toàn' },
  { character: '常', pinyin: 'cháng', hanViet: 'thường', meaning: 'thường, bình thường' },
  { character: '跟', pinyin: 'gēn', hanViet: 'cân', meaning: 'theo, với' },
  { character: '走', pinyin: 'zǒu', hanViet: 'tẩu', meaning: 'đi' },
  { character: '超', pinyin: 'chāo', hanViet: 'siêu', meaning: 'vượt, siêu' },
  { character: '市', pinyin: 'shì', hanViet: 'thị', meaning: 'chợ, thành phố' },
  { character: '练', pinyin: 'liàn', hanViet: 'luyện', meaning: 'luyện tập' },
  { character: '做', pinyin: 'zuò', hanViet: 'tố', meaning: 'làm' },
  { character: '借', pinyin: 'jiè', hanViet: 'tá', meaning: 'mượn' },
  { character: '时', pinyin: 'shí', hanViet: 'thời', meaning: 'thời gian, giờ' },
  { character: '候', pinyin: 'hòu', hanViet: 'hậu', meaning: 'lúc, thời điểm' },
  { character: '看', pinyin: 'kàn', hanViet: 'khán', meaning: 'xem, nhìn' },
  { character: '视', pinyin: 'shì', hanViet: 'thị', meaning: 'nhìn, xem' },
  { character: '舍', pinyin: 'shè', hanViet: 'xá', meaning: 'ký túc xá, nhà' },
  { character: '正', pinyin: 'zhèng', hanViet: 'chính', meaning: 'đúng, chính' },
  { character: '录', pinyin: 'lù', hanViet: 'lục', meaning: 'ghi chép, thu âm' },
  { character: '教', pinyin: 'jiào', hanViet: 'giáo', meaning: 'dạy' },
  { character: '乐', pinyin: 'yuè', hanViet: 'nhạc', meaning: 'âm nhạc' },
  { character: '事', pinyin: 'shì', hanViet: 'sự', meaning: 'việc' },
  { character: '想', pinyin: 'xiǎng', hanViet: 'tưởng', meaning: 'nghĩ, muốn' },
  { character: '坐', pinyin: 'zuò', hanViet: 'tọa', meaning: 'ngồi' },
  { character: '护', pinyin: 'hù', hanViet: 'hộ', meaning: 'bảo vệ' },
  { character: '课', pinyin: 'kè', hanViet: 'khóa', meaning: 'bài học, tiết học' },
  { character: '合', pinyin: 'hé', hanViet: 'hợp', meaning: 'hợp, hợp lại' },
  { character: '力', pinyin: 'lì', hanViet: 'lực', meaning: 'sức lực' },
  { character: '化', pinyin: 'huà', hanViet: 'hóa', meaning: 'biến hóa, hóa' },
  { character: '飞', pinyin: 'fēi', hanViet: 'phi', meaning: 'bay' },
  { character: '火', pinyin: 'huǒ', hanViet: 'hỏa', meaning: 'lửa' },
  { character: '寄', pinyin: 'jì', hanViet: 'ký', meaning: 'gửi' },
  { character: '代', pinyin: 'dài', hanViet: 'đại', meaning: 'thay, thay mặt' },
  { character: '表', pinyin: 'biǎo', hanViet: 'biểu', meaning: 'bảng, biểu hiện' },
  { character: '参', pinyin: 'cān', hanViet: 'tham', meaning: 'tham gia' },
  { character: '观', pinyin: 'guān', hanViet: 'quan', meaning: 'xem, quan sát' },
  { character: '当', pinyin: 'dāng', hanViet: 'đương', meaning: 'làm, đảm nhiệm' },
  { character: '顺', pinyin: 'shùn', hanViet: 'thuận', meaning: 'thuận lợi' },
  { character: '便', pinyin: 'biàn', hanViet: 'tiện', meaning: 'tiện, thuận tiện' },
  { character: '替', pinyin: 'tì', hanViet: 'thế', meaning: 'thay thế' },
  { character: '拿', pinyin: 'ná', hanViet: 'nã', meaning: 'cầm, lấy' },
  { character: '帮', pinyin: 'bāng', hanViet: 'bang', meaning: 'giúp, giúp đỡ' },
  { character: '可', pinyin: 'kě', hanViet: 'khả', meaning: 'có thể' },
  { character: '以', pinyin: 'yǐ', hanViet: 'dĩ', meaning: 'lấy, dùng, có thể' },
  { character: '试', pinyin: 'shì', hanViet: 'thí', meaning: 'thử, thi' },
  { character: '羽', pinyin: 'yǔ', hanViet: 'vũ', meaning: 'lông vũ' },
  { character: '然', pinyin: 'rán', hanViet: 'nhiên', meaning: 'như vậy, nhưng' },
  { character: '适', pinyin: 'shì', hanViet: 'thích', meaning: 'phù hợp' },
  { character: '短', pinyin: 'duǎn', hanViet: 'đoản', meaning: 'ngắn' },
  { character: '种', pinyin: 'zhǒng', hanViet: 'chủng', meaning: 'loại, giống' },
  { character: '贵', pinyin: 'guì', hanViet: 'quý', meaning: 'đắt, quý' },
  { character: '宜', pinyin: 'yí', hanViet: 'nghi', meaning: 'phù hợp, nên' },
  { character: '深', pinyin: 'shēn', hanViet: 'thâm', meaning: 'sâu' },
  { character: '浅', pinyin: 'qiǎn', hanViet: 'thiển', meaning: 'nông, cạn' },
  { character: '肥', pinyin: 'féi', hanViet: 'phì', meaning: 'béo, mập' },
  { character: '年', pinyin: 'nián', hanViet: 'niên', meaning: 'năm' },
  { character: '岁', pinyin: 'suì', hanViet: 'tuế', meaning: 'tuổi' },
  { character: '祝', pinyin: 'zhù', hanViet: 'chúc', meaning: 'chúc mừng' },
  { character: '快', pinyin: 'kuài', hanViet: 'khoái', meaning: 'nhanh, vui' },
  { character: '过', pinyin: 'guò', hanViet: 'quá', meaning: 'qua, trải qua' },
  { character: '定', pinyin: 'dìng', hanViet: 'định', meaning: 'định, xác định' },
  { character: '毕', pinyin: 'bì', hanViet: 'tất', meaning: 'hoàn tất' },
  { character: '业', pinyin: 'yè', hanViet: 'nghiệp', meaning: 'nghề, nghiệp' },
  { character: '举', pinyin: 'jǔ', hanViet: 'cử', meaning: 'giơ lên, tổ chức' },
  { character: '出', pinyin: 'chū', hanViet: 'xuất', meaning: 'ra, xuất hiện' },
  { character: '打', pinyin: 'dǎ', hanViet: 'đả', meaning: 'đánh, gọi điện' },
  { character: '准', pinyin: 'zhǔn', hanViet: 'chuẩn', meaning: 'chuẩn, chính xác' },
  { character: '备', pinyin: 'bèi', hanViet: 'bị', meaning: 'chuẩn bị' },
  { character: '加', pinyin: 'jiā', hanViet: 'gia', meaning: 'thêm, cộng' },
  { character: '早', pinyin: 'zǎo', hanViet: 'tảo', meaning: 'sớm' },
  { character: '半', pinyin: 'bàn', hanViet: 'bán', meaning: 'một nửa' },
  { character: '床', pinyin: 'chuáng', hanViet: 'sàng', meaning: 'giường' },
  { character: '洗', pinyin: 'xǐ', hanViet: 'tẩy', meaning: 'rửa, giặt' },
  { character: '澡', pinyin: 'zǎo', hanViet: 'tảo', meaning: 'tắm' },
  { character: '操', pinyin: 'cāo', hanViet: 'thao', meaning: 'thao tác, tập thể dục' },
  { character: '场', pinyin: 'chǎng', hanViet: 'trường', meaning: 'sân, nơi chốn' },
  { character: '锻', pinyin: 'duàn', hanViet: 'đoán', meaning: 'rèn luyện' },
  { character: '炼', pinyin: 'liàn', hanViet: 'luyện', meaning: 'luyện, rèn' },
  { character: '睡', pinyin: 'shuì', hanViet: 'thụy', meaning: 'ngủ' },
  { character: '山', pinyin: 'shān', hanViet: 'sơn', meaning: 'núi' },
  { character: '级', pinyin: 'jí', hanViet: 'cấp', meaning: 'cấp, bậc' },
  { character: '前', pinyin: 'qián', hanViet: 'tiền', meaning: 'trước' },
  { character: '己', pinyin: 'jǐ', hanViet: 'kỷ', meaning: 'bản thân' },
  { character: '爱', pinyin: 'ài', hanViet: 'ái', meaning: 'yêu, thích' },
  { character: '非', pinyin: 'fēi', hanViet: 'phi', meaning: 'không phải' },
  { character: '特', pinyin: 'tè', hanViet: 'đặc', meaning: 'đặc biệt' },
  { character: '让', pinyin: 'ràng', hanViet: 'nhượng', meaning: 'nhường, để cho' },
  { character: '谈', pinyin: 'tán', hanViet: 'đàm', meaning: 'nói chuyện, bàn luận' },
  { character: '喜', pinyin: 'xǐ', hanViet: 'hỉ', meaning: 'vui, thích' },
  { character: '剧', pinyin: 'jù', hanViet: 'kịch', meaning: 'kịch, phim' },
  { character: '高', pinyin: 'gāo', hanViet: 'cao', meaning: 'cao' },
  { character: '感', pinyin: 'gǎn', hanViet: 'cảm', meaning: 'cảm thấy, cảm giác' },
  { character: '兴', pinyin: 'xìng', hanViet: 'hứng', meaning: 'hứng thú' },
  { character: '趣', pinyin: 'qù', hanViet: 'thú', meaning: 'thú vị, hứng thú' },
  { character: '地', pinyin: 'dì', hanViet: 'địa', meaning: 'đất, nơi' },
  { character: '派', pinyin: 'pài', hanViet: 'phái', meaning: 'phái, cử đi' },
  { character: '余', pinyin: 'yú', hanViet: 'dư', meaning: 'dư, thừa' },
  { character: '从', pinyin: 'cóng', hanViet: 'tòng', meaning: 'từ, theo' },
  { character: '到', pinyin: 'dào', hanViet: 'đáo', meaning: 'đến' },
  { character: '直', pinyin: 'zhí', hanViet: 'trực', meaning: 'thẳng, trực tiếp' },
  { character: '里', pinyin: 'lǐ', hanViet: 'lí', meaning: 'trong, bên trong' },
  { character: '左', pinyin: 'zuǒ', hanViet: 'tả', meaning: 'trái, bên trái' },
  { character: '右', pinyin: 'yòu', hanViet: 'hữu', meaning: 'phải, bên phải' },
  { character: '南', pinyin: 'nán', hanViet: 'nam', meaning: 'phía nam' },
  { character: '边', pinyin: 'biān', hanViet: 'biên', meaning: 'bên, cạnh' },
  { character: '间', pinyin: 'jiān', hanViet: 'gian', meaning: 'phòng, khoảng' },
  { character: '足', pinyin: 'zú', hanViet: 'túc', meaning: 'chân, đủ' },
  { character: '球', pinyin: 'qiú', hanViet: 'cầu', meaning: 'bóng' },
  { character: '远', pinyin: 'yuǎn', hanViet: 'viễn', meaning: 'xa' },
  { character: '灯', pinyin: 'dēng', hanViet: 'đăng', meaning: 'đèn' },
  { character: '往', pinyin: 'wǎng', hanViet: 'vãng', meaning: 'đi, hướng tới' },
  { character: '路', pinyin: 'lù', hanViet: 'lộ', meaning: 'đường' },
  { character: '会', pinyin: 'huì', hanViet: 'hội', meaning: 'biết, sẽ' },
  { character: '次', pinyin: 'cì', hanViet: 'thứ', meaning: 'lần, thứ' },
  { character: '极', pinyin: 'jí', hanViet: 'cực', meaning: 'rất, cực' },
  { character: '能', pinyin: 'néng', hanViet: 'năng', meaning: 'có thể' },
  { character: '舒', pinyin: 'shū', hanViet: 'thư', meaning: 'thoải mái' },
  { character: '育', pinyin: 'yù', hanViet: 'dục', meaning: 'giáo dục' },
  { character: '报', pinyin: 'bào', hanViet: 'báo', meaning: 'báo, báo cáo' },
  { character: '懂', pinyin: 'dǒng', hanViet: 'đổng', meaning: 'hiểu' },
  { character: '请', pinyin: 'qǐng', hanViet: 'thỉnh', meaning: 'mời, xin' },
  { character: '始', pinyin: 'shǐ', hanViet: 'thủy', meaning: 'bắt đầu' },
  { character: '疼', pinyin: 'téng', hanViet: 'đằng', meaning: 'đau' },
  { character: '病', pinyin: 'bìng', hanViet: 'bệnh', meaning: 'bệnh' },
  { character: '意', pinyin: 'yì', hanViet: 'ý', meaning: 'ý, ý nghĩa' },
  { character: '思', pinyin: 'sī', hanViet: 'tư', meaning: 'nghĩ' },
  { character: '为', pinyin: 'wéi', hanViet: 'vi', meaning: 'làm, vì' },
  { character: '步', pinyin: 'bù', hanViet: 'bộ', meaning: 'bước' },
  { character: '平', pinyin: 'píng', hanViet: 'bình', meaning: 'bằng, bình' },
  { character: '坚', pinyin: 'jiān', hanViet: 'kiên', meaning: 'vững, kiên cố' },
  { character: '持', pinyin: 'chí', hanViet: 'trì', meaning: 'cầm, giữ, kiên trì' },
  { character: '错', pinyin: 'cuò', hanViet: 'thác', meaning: 'sai, lỗi' },
  { character: '认', pinyin: 'rèn', hanViet: 'nhận', meaning: 'nhận, nhận biết' },
  { character: '真', pinyin: 'zhēn', hanViet: 'chân', meaning: 'thật, chân thật' },
  { character: '运', pinyin: 'yùn', hanViet: 'vận', meaning: 'vận chuyển, vận động' },
  { character: '动', pinyin: 'dòng', hanViet: 'động', meaning: 'động, vận động' },
  { character: '跑', pinyin: 'pǎo', hanViet: 'bào', meaning: 'chạy' },
  { character: '才', pinyin: 'cái', hanViet: 'tài', meaning: 'mới, tài năng' },
  { character: '目', pinyin: 'mù', hanViet: 'mục', meaning: 'mắt, mục' },
  { character: '愿', pinyin: 'yuàn', hanViet: 'nguyện', meaning: 'mong muốn' },
  { character: '因', pinyin: 'yīn', hanViet: 'nhân', meaning: 'vì, nguyên nhân' },
  { character: '拉', pinyin: 'lā', hanViet: 'lạp', meaning: 'kéo' },
  { character: '肚', pinyin: 'dù', hanViet: 'đỗ', meaning: 'bụng' },
  { character: '厉', pinyin: 'lì', hanViet: 'lệ', meaning: 'nghiêm khắc, lợi hại' },
  { character: '害', pinyin: 'hài', hanViet: 'hại', meaning: 'hại' },
  { character: '鱼', pinyin: 'yú', hanViet: 'ngư', meaning: 'cá' },
  { character: '肉', pinyin: 'ròu', hanViet: 'nhục', meaning: 'thịt' },
  { character: '检', pinyin: 'jiǎn', hanViet: 'kiểm', meaning: 'kiểm tra' },
  { character: '查', pinyin: 'chá', hanViet: 'tra', meaning: 'tra, kiểm tra' },
  { character: '消', pinyin: 'xiāo', hanViet: 'tiêu', meaning: 'tiêu tan, mất đi' },
  { character: '牛', pinyin: 'niú', hanViet: 'ngưu', meaning: 'trâu, bò' },
  { character: '等', pinyin: 'děng', hanViet: 'đẳng', meaning: 'đợi, vân vân' },
  { character: '炎', pinyin: 'yán', hanViet: 'viêm', meaning: 'viêm, nóng' },
  { character: '结', pinyin: 'jié', hanViet: 'kết', meaning: 'kết, kết thúc' },
  { character: '跳', pinyin: 'tiào', hanViet: 'khiêu', meaning: 'nhảy' },
  { character: '药', pinyin: 'yào', hanViet: 'dược', meaning: 'thuốc' },
  { character: '光', pinyin: 'guāng', hanViet: 'quang', meaning: 'ánh sáng' },
  { character: '交', pinyin: 'jiāo', hanViet: 'giao', meaning: 'giao, trao đổi' },
  { character: '通', pinyin: 'tōng', hanViet: 'thông', meaning: 'thông suốt, giao thông' },
  { character: '河', pinyin: 'hé', hanViet: 'hà', meaning: 'sông' },
  { character: '共', pinyin: 'gòng', hanViet: 'cộng', meaning: 'cùng, chung' },
  { character: '房', pinyin: 'fáng', hanViet: 'phòng', meaning: 'phòng, nhà' },
  { character: '朝', pinyin: 'cháo', hanViet: 'triều', meaning: 'hướng về, triều đại' },
  { character: '周', pinyin: 'zhōu', hanViet: 'chu', meaning: 'tuần, vòng quanh' },
  { character: '围', pinyin: 'wéi', hanViet: 'vi', meaning: 'vây quanh' },
  { character: '环', pinyin: 'huán', hanViet: 'hoàn', meaning: 'vòng, vòng quanh' },
  { character: '境', pinyin: 'jìng', hanViet: 'cảnh', meaning: 'cảnh, môi trường' },
  { character: '乱', pinyin: 'luàn', hanViet: 'loạn', meaning: 'loạn, lộn xộn' },
  { character: '层', pinyin: 'céng', hanViet: 'tầng', meaning: 'tầng, lớp' },
  { character: '虽', pinyin: 'suī', hanViet: 'tuy', meaning: 'tuy, mặc dù' },
  { character: '站', pinyin: 'zhàn', hanViet: 'trạm', meaning: 'đứng, trạm' },
  { character: '干', pinyin: 'gān', hanViet: 'can', meaning: 'khô; làm' },
  { character: '完', pinyin: 'wán', hanViet: 'hoàn', meaning: 'xong, hoàn thành' },
  { character: '页', pinyin: 'yè', hanViet: 'diệp', meaning: 'trang' },
  { character: '成', pinyin: 'chéng', hanViet: 'thành', meaning: 'trở thành, hoàn thành' },
  { character: '故', pinyin: 'gù', hanViet: 'cố', meaning: 'cũ, nguyên nhân' },
  { character: '笑', pinyin: 'xiào', hanViet: 'tiếu', meaning: 'cười' },
  { character: '念', pinyin: 'niàn', hanViet: 'niệm', meaning: 'đọc, nhớ' },
  { character: '句', pinyin: 'jù', hanViet: 'cú', meaning: 'câu' },
  { character: '题', pinyin: 'tí', hanViet: 'đề', meaning: 'đề bài, chủ đề' },
  { character: '糟', pinyin: 'zāo', hanViet: 'tao', meaning: 'tệ, hỏng' },
  { character: '糕', pinyin: 'gāo', hanViet: 'cao', meaning: 'bánh ngọt' },
  { character: '满', pinyin: 'mǎn', hanViet: 'mãn', meaning: 'đầy, hài lòng' },
  { character: '原', pinyin: 'yuán', hanViet: 'nguyên', meaning: 'ban đầu, nguyên gốc' },
  { character: '班', pinyin: 'bān', hanViet: 'ban', meaning: 'lớp, ca' },
  { character: '功', pinyin: 'gōng', hanViet: 'công', meaning: 'công lao, công phu' },
  { character: '游', pinyin: 'yóu', hanViet: 'du', meaning: 'bơi, đi chơi' },
  { character: '泳', pinyin: 'yǒng', hanViet: 'vịnh', meaning: 'bơi' },
  { character: '惯', pinyin: 'guàn', hanViet: 'quán', meaning: 'quen, thói quen' },
  { character: '效', pinyin: 'xiào', hanViet: 'hiệu', meaning: 'hiệu quả' },
  { character: '果', pinyin: 'guǒ', hanViet: 'quả', meaning: 'quả, kết quả' },
  { character: '处', pinyin: 'chù', hanViet: 'xứ', meaning: 'nơi, chỗ' },
  { character: '失', pinyin: 'shī', hanViet: 'thất', meaning: 'mất' },
  { character: '必', pinyin: 'bì', hanViet: 'tất', meaning: 'chắc chắn, nhất định' },
  { character: '须', pinyin: 'xū', hanViet: 'tu', meaning: 'phải, cần' },
  { character: '散', pinyin: 'sàn', hanViet: 'tán', meaning: 'tan, giải tán' },
  { character: '钟', pinyin: 'zhōng', hanViet: 'chung', meaning: 'chuông, đồng hồ' },
  { character: '血', pinyin: 'xuè', hanViet: 'huyết', meaning: 'máu' },
  { character: '挺', pinyin: 'tǐng', hanViet: 'đĩnh', meaning: 'rất, thẳng' },
  { character: '变', pinyin: 'biàn', hanViet: 'biến', meaning: 'thay đổi' },
  { character: '迷', pinyin: 'mí', hanViet: 'mê', meaning: 'mê, lạc' },
  { character: '古', pinyin: 'gǔ', hanViet: 'cổ', meaning: 'xưa, cổ' },
  { character: '商', pinyin: 'shāng', hanViet: 'thương', meaning: 'buôn bán, thương mại' },
  { character: '响', pinyin: 'xiǎng', hanViet: 'hưởng', meaning: 'vang, kêu' },
  { character: '曲', pinyin: 'qǔ', hanViet: 'khúc', meaning: 'bài hát, khúc' },
  { character: '城', pinyin: 'chéng', hanViet: 'thành', meaning: 'thành phố, thành trì' },
  { character: '漂', pinyin: 'piào', hanViet: 'phiêu', meaning: 'đẹp, trôi' },
  { character: '亮', pinyin: 'liàng', hanViet: 'lượng', meaning: 'sáng, đẹp' },
  { character: '流', pinyin: 'liú', hanViet: 'lưu', meaning: 'chảy' },
  { character: '增', pinyin: 'zēng', hanViet: 'tăng', meaning: 'tăng thêm' },
  { character: '更', pinyin: 'gèng', hanViet: 'canh', meaning: 'hơn, càng' },
  { character: '温', pinyin: 'wēn', hanViet: 'ôn', meaning: 'ấm, nhiệt độ' },
  { character: '暖', pinyin: 'nuǎn', hanViet: 'noãn', meaning: 'ấm áp' },
  { character: '度', pinyin: 'dù', hanViet: 'độ', meaning: 'độ, mức độ' },
  { character: '轻', pinyin: 'qīng', hanViet: 'khinh', meaning: 'nhẹ' },
  { character: '春', pinyin: 'chūn', hanViet: 'xuân', meaning: 'mùa xuân' },
  { character: '季', pinyin: 'jì', hanViet: 'quý', meaning: 'mùa, quý' },
  { character: '夏', pinyin: 'xià', hanViet: 'hạ', meaning: 'mùa hè' },
  { character: '秋', pinyin: 'qiū', hanViet: 'thu', meaning: 'mùa thu' },
  { character: '冬', pinyin: 'dōng', hanViet: 'đông', meaning: 'mùa đông' },
  { character: '冷', pinyin: 'lěng', hanViet: 'lãnh', meaning: 'lạnh' },
  { character: '乡', pinyin: 'xiāng', hanViet: 'hương', meaning: 'quê hương' },
  { character: '刮', pinyin: 'guā', hanViet: 'quát', meaning: 'cạo, thổi' },
  { character: '风', pinyin: 'fēng', hanViet: 'phong', meaning: 'gió' },
  { character: '夜', pinyin: 'yè', hanViet: 'dạ', meaning: 'đêm' },
  { character: '而', pinyin: 'ér', hanViet: 'nhi', meaning: 'mà, nhưng' },
  { character: '且', pinyin: 'qiě', hanViet: 'thả', meaning: 'hơn nữa, tạm thời' },
  { character: '历', pinyin: 'lì', hanViet: 'lịch', meaning: 'trải qua, lịch sử' },
  { character: '史', pinyin: 'shǐ', hanViet: 'sử', meaning: 'lịch sử' },
  { character: '改', pinyin: 'gǎi', hanViet: 'cải', meaning: 'thay đổi, sửa' },
  { character: '放', pinyin: 'fàng', hanViet: 'phóng', meaning: 'thả, đặt' },
  { character: '叶', pinyin: 'yè', hanViet: 'diệp', meaning: 'lá' },
  { character: '区', pinyin: 'qū', hanViet: 'khu', meaning: 'khu vực' },
  { character: '落', pinyin: 'luò', hanViet: 'lạc', meaning: 'rơi, rụng' },
  { character: '冰', pinyin: 'bīng', hanViet: 'băng', meaning: 'băng, nước đá' },
  { character: '未', pinyin: 'wèi', hanViet: 'vị', meaning: 'chưa' },
  { character: '雪', pinyin: 'xuě', hanViet: 'tuyết', meaning: 'tuyết' },
  { character: '着', pinyin: 'zhe', hanViet: 'trứ', meaning: 'đang, mặc' },
  { character: '急', pinyin: 'jí', hanViet: 'cấp', meaning: 'gấp, vội' },
  { character: '坏', pinyin: 'huài', hanViet: 'hoại', meaning: 'xấu, hỏng' },
  { character: '停', pinyin: 'tíng', hanViet: 'đình', meaning: 'dừng' },
  { character: '该', pinyin: 'gāi', hanViet: 'cai', meaning: 'nên, phải' },
  { character: '迟', pinyin: 'chí', hanViet: 'trì', meaning: 'muộn, chậm' },
  { character: '尤', pinyin: 'yóu', hanViet: 'vưu', meaning: 'đặc biệt' },
  { character: '其', pinyin: 'qí', hanViet: 'kỳ', meaning: 'nó, của nó' },
  { character: '母', pinyin: 'mǔ', hanViet: 'mẫu', meaning: 'mẹ' },
  { character: '亲', pinyin: 'qīn', hanViet: 'thân', meaning: 'thân, cha mẹ' },
  { character: '告', pinyin: 'gào', hanViet: 'cáo', meaning: 'báo, nói' },
  { character: '诉', pinyin: 'sù', hanViet: 'tố', meaning: 'kể, tố cáo' },
  { character: '辛', pinyin: 'xīn', hanViet: 'tân', meaning: 'cay, vất vả' },
  { character: '苦', pinyin: 'kǔ', hanViet: 'khổ', meaning: 'khổ, đắng' },
  { character: '麻', pinyin: 'má', hanViet: 'ma', meaning: 'tê, gai dầu' },
  { character: '烦', pinyin: 'fán', hanViet: 'phiền', meaning: 'phiền' },
  { character: '送', pinyin: 'sòng', hanViet: 'tống', meaning: 'tiễn, đưa' },
  { character: '展', pinyin: 'zhǎn', hanViet: 'triển', meaning: 'triển lãm, mở ra' },
  { character: '览', pinyin: 'lǎn', hanViet: 'lãm', meaning: 'xem, ngắm' },
  { character: '忘', pinyin: 'wàng', hanViet: 'vong', meaning: 'quên' },
  { character: '座', pinyin: 'zuò', hanViet: 'tọa', meaning: 'chỗ ngồi' },
  { character: '注', pinyin: 'zhù', hanViet: 'chú', meaning: 'chú ý, ghi chú' },
  { character: '约', pinyin: 'yuē', hanViet: 'ước', meaning: 'hẹn, khoảng' },
  { character: '求', pinyin: 'qiú', hanViet: 'cầu', meaning: 'cầu, yêu cầu' },
  { character: '清', pinyin: 'qīng', hanViet: 'thanh', meaning: 'trong, sạch' },
  { character: '楚', pinyin: 'chǔ', hanViet: 'sở', meaning: 'rõ ràng' },
  { character: '记', pinyin: 'jì', hanViet: 'ký', meaning: 'ghi nhớ' },
  { character: '使', pinyin: 'shǐ', hanViet: 'sử', meaning: 'khiến, sử dụng' },
  { character: '摸', pinyin: 'mō', hanViet: 'mạc', meaning: 'sờ, mò' },
  { character: '按', pinyin: 'àn', hanViet: 'án', meaning: 'ấn, bấm' },
  { character: '摩', pinyin: 'mó', hanViet: 'ma', meaning: 'xoa, mài' },
  { character: '针', pinyin: 'zhēn', hanViet: 'châm', meaning: 'kim, châm cứu' },
  { character: '灸', pinyin: 'jiǔ', hanViet: 'cứu', meaning: 'cứu ngải' },
  { character: '细', pinyin: 'xì', hanViet: 'tế', meaning: 'nhỏ, tỉ mỉ' },
  { character: '烤', pinyin: 'kǎo', hanViet: 'khảo', meaning: 'nướng' },
  { character: '第', pinyin: 'dì', hanViet: 'đệ', meaning: 'thứ' },
  { character: '餐', pinyin: 'cān', hanViet: 'xan', meaning: 'bữa ăn' },
  { character: '糖', pinyin: 'táng', hanViet: 'đường', meaning: 'đường' },
  { character: '钢', pinyin: 'gāng', hanViet: 'cương', meaning: 'thép' },
  { character: '琴', pinyin: 'qín', hanViet: 'cầm', meaning: 'đàn' },
  { character: '耳', pinyin: 'ěr', hanViet: 'nhĩ', meaning: 'tai' },
  { character: '奏', pinyin: 'zòu', hanViet: 'tấu', meaning: 'biểu diễn, tấu nhạc' },
  { character: '导', pinyin: 'dǎo', hanViet: 'đạo', meaning: 'dẫn, hướng dẫn' },
  { character: '需', pinyin: 'xū', hanViet: 'nhu', meaning: 'cần, nhu cầu' },
  { character: '纽', pinyin: 'niǔ', hanViet: 'nữu', meaning: 'nút, nút thắt' },
  { character: '织', pinyin: 'zhī', hanViet: 'chức', meaning: 'dệt, đan' },
  { character: '收', pinyin: 'shōu', hanViet: 'thu', meaning: 'thu, nhận' },
  { character: '利', pinyin: 'lì', hanViet: 'lợi', meaning: 'lợi, lợi ích' },
  { character: '铁', pinyin: 'tiě', hanViet: 'thiết', meaning: 'sắt' },
  { character: '由', pinyin: 'yóu', hanViet: 'do', meaning: 'do, bởi, từ' },
  { character: '鼻', pinyin: 'bí', hanViet: 'tị', meaning: 'mũi' },
  { character: '眼', pinyin: 'yǎn', hanViet: 'nhãn', meaning: 'mắt' },
  { character: '量', pinyin: 'liàng', hanViet: 'lượng', meaning: 'lượng, đo lường' },
  { character: '互', pinyin: 'hù', hanViet: 'hỗ', meaning: 'lẫn nhau' },
  { character: '相', pinyin: 'xiāng', hanViet: 'tương', meaning: 'lẫn nhau, tương hỗ' },
  { character: '助', pinyin: 'zhù', hanViet: 'trợ', meaning: 'giúp đỡ' },
  { character: '照', pinyin: 'zhào', hanViet: 'chiếu', meaning: 'chiếu sáng, chăm sóc' },
  { character: '签', pinyin: 'qiān', hanViet: 'thiêm', meaning: 'ký tên' },
  { character: '证', pinyin: 'zhèng', hanViet: 'chứng', meaning: 'chứng nhận, giấy tờ' },
  { character: '袋', pinyin: 'dài', hanViet: 'đại', meaning: 'túi' },
  { character: '麦', pinyin: 'mài', hanViet: 'mạch', meaning: 'lúa mì' },
  { character: '程', pinyin: 'chéng', hanViet: 'trình', meaning: 'quá trình, trình tự' },
  { character: '承', pinyin: 'chéng', hanViet: 'thừa', meaning: 'nhận, gánh vác' },
  { character: '狂', pinyin: 'kuáng', hanViet: 'cuồng', meaning: 'điên cuồng' },
  { character: '精', pinyin: 'jīng', hanViet: 'tinh', meaning: 'tinh thần, tinh hoa' },
  { character: '神', pinyin: 'shén', hanViet: 'thần', meaning: 'thần, tinh thần' },
  { character: '赛', pinyin: 'sài', hanViet: 'tái', meaning: 'thi đấu, cuộc thi' },
  { character: '贴', pinyin: 'tiē', hanViet: 'thiếp', meaning: 'dán' },
  { character: '暂', pinyin: 'zàn', hanViet: 'tạm', meaning: 'tạm thời' },
  { character: '营', pinyin: 'yíng', hanViet: 'doanh', meaning: 'doanh trại, kinh doanh' },
  { character: '辞', pinyin: 'cí', hanViet: 'từ', meaning: 'từ chối, từ biệt' },
  { character: '棒', pinyin: 'bàng', hanViet: 'bổng', meaning: 'gậy, tuyệt' },
  { character: '之', pinyin: 'zhī', hanViet: 'chi', meaning: 'của, nó' },
  { character: '引', pinyin: 'yǐn', hanViet: 'dẫn', meaning: 'dẫn, kéo' },
  { character: '闭', pinyin: 'bì', hanViet: 'bế', meaning: 'đóng' },
  { character: '油', pinyin: 'yóu', hanViet: 'du', meaning: 'dầu' },
  { character: '画', pinyin: 'huà', hanViet: 'họa', meaning: 'vẽ, tranh' },
  { character: '倍', pinyin: 'bèi', hanViet: 'bội', meaning: 'gấp bội' },
  { character: '镜', pinyin: 'jìng', hanViet: 'kính', meaning: 'gương, kính' },
  { character: '摔', pinyin: 'shuāi', hanViet: 'suất', meaning: 'ngã, làm rơi' },
  { character: '碰', pinyin: 'pèng', hanViet: 'bính', meaning: 'đụng, va chạm' },
  { character: '造', pinyin: 'zào', hanViet: 'tạo', meaning: 'tạo ra, chế tạo' },
  { character: '掉', pinyin: 'diào', hanViet: 'điệu', meaning: 'rơi, mất' },
  { character: '遵', pinyin: 'zūn', hanViet: 'tuân', meaning: 'tuân theo' },
  { character: '守', pinyin: 'shǒu', hanViet: 'thủ', meaning: 'giữ, tuân thủ' },
  { character: '规', pinyin: 'guī', hanViet: 'quy', meaning: 'quy tắc' },
  { character: '则', pinyin: 'zé', hanViet: 'tắc', meaning: 'quy tắc, thì' },
  { character: '保', pinyin: 'bǎo', hanViet: 'bảo', meaning: 'bảo vệ' },
  { character: '各', pinyin: 'gè', hanViet: 'các', meaning: 'mỗi, các' },
  { character: '挑', pinyin: 'tiāo', hanViet: 'thiêu', meaning: 'chọn, gánh' },
  { character: '选', pinyin: 'xuǎn', hanViet: 'tuyển', meaning: 'chọn' },
  { character: '除', pinyin: 'chú', hanViet: 'trừ', meaning: 'loại bỏ, trừ' },
  { character: '拍', pinyin: 'pāi', hanViet: 'phách', meaning: 'vỗ, chụp' },
  { character: '盒', pinyin: 'hé', hanViet: 'hạp', meaning: 'hộp' },
  { character: '纸', pinyin: 'zhǐ', hanViet: 'chỉ', meaning: 'giấy' },
  { character: '累', pinyin: 'lèi', hanViet: 'lũy', meaning: 'mệt' },
  { character: '困', pinyin: 'kùn', hanViet: 'khốn', meaning: 'buồn ngủ, khó khăn' },
  { character: '修', pinyin: 'xiū', hanViet: 'tu', meaning: 'sửa, tu sửa' },
  { character: '爬', pinyin: 'pá', hanViet: 'ba', meaning: 'leo, bò' },
  { character: '钥', pinyin: 'yào', hanViet: 'thược', meaning: 'chìa khóa' },
  { character: '匙', pinyin: 'shi', hanViet: 'thìa', meaning: 'chìa khóa, thìa' },
  { character: '却', pinyin: 'què', hanViet: 'khước', meaning: 'nhưng, lại' },
  { character: '拔', pinyin: 'bá', hanViet: 'bạt', meaning: 'nhổ, rút' },
  { character: '根', pinyin: 'gēn', hanViet: 'căn', meaning: 'rễ, gốc' },
  { character: '据', pinyin: 'jù', hanViet: 'cứ', meaning: 'dựa theo, căn cứ' },
  { character: '扛', pinyin: 'káng', hanViet: 'giang', meaning: 'vác' },
  { character: '伙', pinyin: 'huǒ', hanViet: 'hỏa', meaning: 'bọn, nhóm' },
  { character: '挂', pinyin: 'guà', hanViet: 'quải', meaning: 'treo' },
  { character: '摆', pinyin: 'bǎi', hanViet: 'bãi', meaning: 'bày, đặt' },
  { character: '摄', pinyin: 'shè', hanViet: 'nhiếp', meaning: 'chụp, quay' },
  { character: '穿', pinyin: 'chuān', hanViet: 'xuyên', meaning: 'mặc, xuyên qua' },
  { character: '裙', pinyin: 'qún', hanViet: 'quần', meaning: 'váy' },
  { character: '讲', pinyin: 'jiǎng', hanViet: 'giảng', meaning: 'nói, giảng' },
  { character: '娘', pinyin: 'niáng', hanViet: 'nương', meaning: 'mẹ, cô gái' },
  { character: '郎', pinyin: 'láng', hanViet: 'lang', meaning: 'chàng trai' },
  { character: '帅', pinyin: 'shuài', hanViet: 'soái', meaning: 'đẹp trai, chỉ huy' },
  { character: '富', pinyin: 'fù', hanViet: 'phú', meaning: 'giàu' },
  { character: '棵', pinyin: 'kē', hanViet: 'khỏa', meaning: 'cây, lượng từ cho cây' },
  { character: '越', pinyin: 'yuè', hanViet: 'việt', meaning: 'vượt qua, càng' },
  { character: '扮', pinyin: 'bàn', hanViet: 'phẫn', meaning: 'hóa trang, đóng vai' },
  { character: '盖', pinyin: 'gài', hanViet: 'cái', meaning: 'đậy, che phủ' },
  { character: '搬', pinyin: 'bān', hanViet: 'ban', meaning: 'chuyển, khuân' },
  { character: '随', pinyin: 'suí', hanViet: 'tùy', meaning: 'theo, tùy' },
  { character: '甜', pinyin: 'tián', hanViet: 'điềm', meaning: 'ngọt' },
  { character: '蛋', pinyin: 'dàn', hanViet: 'đản', meaning: 'trứng' },
  { character: '装', pinyin: 'zhuāng', hanViet: 'trang', meaning: 'trang phục, lắp đặt' },
  { character: '饰', pinyin: 'shì', hanViet: 'sức', meaning: 'trang sức, trang trí' },
  { character: '联', pinyin: 'lián', hanViet: 'liên', meaning: 'liên kết' },
  { character: '置', pinyin: 'zhì', hanViet: 'trí', meaning: 'đặt, sắp đặt' },
  { character: '管', pinyin: 'guǎn', hanViet: 'quản', meaning: 'quản lý, ống' },
  { character: '擦', pinyin: 'cā', hanViet: 'sát', meaning: 'lau, chà' },
  { character: '圆', pinyin: 'yuán', hanViet: 'viên', meaning: 'tròn' },
  { character: '板', pinyin: 'bǎn', hanViet: 'bản', meaning: 'bảng, tấm' },
  { character: '窗', pinyin: 'chuāng', hanViet: 'song', meaning: 'cửa sổ' },
  { character: '祥', pinyin: 'xiáng', hanViet: 'tường', meaning: 'may mắn, tốt lành' },
  { character: '旺', pinyin: 'wàng', hanViet: 'vượng', meaning: 'thịnh vượng' },
  { character: '幸', pinyin: 'xìng', hanViet: 'hạnh', meaning: 'may mắn' },
  { character: '福', pinyin: 'fú', hanViet: 'phúc', meaning: 'phúc, hạnh phúc' },
  { character: '卡', pinyin: 'qiǎ', hanViet: 'tạp', meaning: 'thẻ' },
  { character: '托', pinyin: 'tuō', hanViet: 'thác', meaning: 'nhờ, nâng đỡ' },
  { character: '捣', pinyin: 'dǎo', hanViet: 'đảo', meaning: 'giã, phá rối' },
  { character: '票', pinyin: 'piào', hanViet: 'phiếu', meaning: 'vé, phiếu' },
  { character: '乘', pinyin: 'chéng', hanViet: 'thừa', meaning: 'đi, ngồi xe' },
  { character: '登', pinyin: 'dēng', hanViet: 'đăng', meaning: 'lên, đăng ký' },
  { character: '续', pinyin: 'xù', hanViet: 'tục', meaning: 'tiếp tục' },
  { character: '顶', pinyin: 'dǐng', hanViet: 'đỉnh', meaning: 'đỉnh, đội' },
  { character: '牌', pinyin: 'pái', hanViet: 'bài', meaning: 'bảng hiệu, thẻ' },
  { character: '调', pinyin: 'diào', hanViet: 'điệu', meaning: 'điều chỉnh, điệu' },
  { character: '被', pinyin: 'bèi', hanViet: 'bị', meaning: 'bị, chăn' },
  { character: '似', pinyin: 'shì', hanViet: 'tự', meaning: 'giống như' },
  { character: '骨', pinyin: 'gǔ', hanViet: 'cốt', meaning: 'xương' },
  { character: '紧', pinyin: 'jǐn', hanViet: 'khẩn', meaning: 'chặt, gấp' },
  { character: '伤', pinyin: 'shāng', hanViet: 'thương', meaning: 'bị thương' },
  { character: '腿', pinyin: 'tuǐ', hanViet: 'thối', meaning: 'chân, đùi' },
  { character: '街', pinyin: 'jiē', hanViet: 'nhai', meaning: 'đường phố' },
  { character: '偷', pinyin: 'tōu', hanViet: 'thâu', meaning: 'trộm, lén' },
  { character: '骗', pinyin: 'piàn', hanViet: 'phiến', meaning: 'lừa gạt' },
  { character: '浪', pinyin: 'làng', hanViet: 'lãng', meaning: 'sóng, lang thang' },
  { character: '费', pinyin: 'fèi', hanViet: 'phí', meaning: 'chi phí, tốn' },
  { character: '遇', pinyin: 'yù', hanViet: 'ngộ', meaning: 'gặp' },
  { character: '傻', pinyin: 'shǎ', hanViet: 'ngốc', meaning: 'ngốc' },
  { character: '罚', pinyin: 'fá', hanViet: 'phạt', meaning: 'phạt' },
  { character: '戒', pinyin: 'jiè', hanViet: 'giới', meaning: 'răn, cai' },
  { character: '猜', pinyin: 'cāi', hanViet: 'sai', meaning: 'đoán' },
  { character: '脸', pinyin: 'liǎn', hanViet: 'kiểm', meaning: 'mặt' },
  { character: '社', pinyin: 'shè', hanViet: 'xã', meaning: 'xã hội' },
  { character: '性', pinyin: 'xìng', hanViet: 'tính', meaning: 'tính chất, giới tính' },
  { character: '格', pinyin: 'gé', hanViet: 'cách', meaning: 'cách, tiêu chuẩn' },
  { character: '艺', pinyin: 'yì', hanViet: 'nghệ', meaning: 'nghệ thuật' },
  { character: '术', pinyin: 'shù', hanViet: 'thuật', meaning: 'kỹ thuật, thuật' },
  { character: '决', pinyin: 'jué', hanViet: 'quyết', meaning: 'quyết định' },
  { character: '担', pinyin: 'dān', hanViet: 'đảm', meaning: 'gánh, đảm nhiệm' },
  { character: '肯', pinyin: 'kěn', hanViet: 'khẳng', meaning: 'chịu, đồng ý' },
  { character: '估', pinyin: 'gū', hanViet: 'cổ', meaning: 'ước tính' },
  { character: '计', pinyin: 'jì', hanViet: 'kế', meaning: 'tính toán, kế hoạch' },
  { character: '慕', pinyin: 'mù', hanViet: 'mộ', meaning: 'ngưỡng mộ' },
  { character: '无', pinyin: 'wú', hanViet: 'vô', meaning: 'không có' },
  { character: '声', pinyin: 'shēng', hanViet: 'thanh', meaning: 'âm thanh' },
  { character: '喘', pinyin: 'chuǎn', hanViet: 'suyễn', meaning: 'thở gấp' },
  { character: '恐', pinyin: 'kǒng', hanViet: 'khủng', meaning: 'sợ' },
  { character: '怕', pinyin: 'pà', hanViet: 'phạ', meaning: 'sợ' },
  { character: '争', pinyin: 'zhēng', hanViet: 'tranh', meaning: 'tranh giành' },
  { character: '胜', pinyin: 'shèng', hanViet: 'thắng', meaning: 'thắng' },
  { character: '危', pinyin: 'wēi', hanViet: 'nguy', meaning: 'nguy hiểm' },
  { character: '险', pinyin: 'xiǎn', hanViet: 'hiểm', meaning: 'nguy hiểm' },
  { character: '积', pinyin: 'jī', hanViet: 'tích', meaning: 'tích lũy' },
  { character: '底', pinyin: 'dǐ', hanViet: 'để', meaning: 'đáy' },
  { character: '背', pinyin: 'bèi', hanViet: 'bối', meaning: 'lưng, thuộc lòng' },
  { character: '纠', pinyin: 'jiū', hanViet: 'củ', meaning: 'sửa, xoắn' },
  { character: '突', pinyin: 'tū', hanViet: 'đột', meaning: 'đột nhiên' },
  { character: '资', pinyin: 'zī', hanViet: 'tư', meaning: 'tài nguyên, vốn' },
  { character: '邀', pinyin: 'yāo', hanViet: 'yêu', meaning: 'mời' },
  { character: '际', pinyin: 'jì', hanViet: 'tế', meaning: 'ranh giới, quốc tế' },
  { character: '播', pinyin: 'bō', hanViet: 'bá', meaning: 'phát sóng, gieo' },
  { character: '址', pinyin: 'zhǐ', hanViet: 'chỉ', meaning: 'địa chỉ' },
  { character: '搞', pinyin: 'gǎo', hanViet: 'cảo', meaning: 'làm, xử lý' },
  { character: '基', pinyin: 'jī', hanViet: 'cơ', meaning: 'nền tảng' },
  { character: '础', pinyin: 'chǔ', hanViet: 'sở', meaning: 'nền móng' },
  { character: '继', pinyin: 'jì', hanViet: 'kế', meaning: 'tiếp tục' },
  { character: '租', pinyin: 'zū', hanViet: 'tô', meaning: 'thuê' },
  { character: '订', pinyin: 'dìng', hanViet: 'đính', meaning: 'đặt' },
  { character: '兵', pinyin: 'bīng', hanViet: 'binh', meaning: 'lính' },
  { character: '俗', pinyin: 'sú', hanViet: 'tục', meaning: 'phong tục, thô tục' },
  { character: '饿', pinyin: 'è', hanViet: 'ngạ', meaning: 'đói' },
  { character: '渴', pinyin: 'kě', hanViet: 'khát', meaning: 'khát' },
  { character: '辣', pinyin: 'là', hanViet: 'lạt', meaning: 'cay' },
  { character: '醋', pinyin: 'cù', hanViet: 'thố', meaning: 'giấm' },
  { character: '零', pinyin: 'líng', hanViet: 'linh', meaning: 'số không' },
  { character: '线', pinyin: 'xiàn', hanViet: 'tuyến', meaning: 'dây, đường' },
  { character: '雕', pinyin: 'diāo', hanViet: 'điêu', meaning: 'điêu khắc' },
  { character: '划', pinyin: 'huà', hanViet: 'hoạch', meaning: 'vạch, chia' },
  { character: '船', pinyin: 'chuán', hanViet: 'thuyền', meaning: 'thuyền' },
  { character: '数', pinyin: 'shù', hanViet: 'số', meaning: 'số, đếm' },
  { character: '族', pinyin: 'zú', hanViet: 'tộc', meaning: 'dân tộc, gia tộc' },
  { character: '伸', pinyin: 'shēn', hanViet: 'thân', meaning: 'duỗi, kéo dài' },
  { character: '松', pinyin: 'sōng', hanViet: 'tùng', meaning: 'cây tùng, lỏng' },
];


/** Auto-assign lesson numbers: every 9 characters = 1 lesson (starting from Bài 1). */
export const CHINESE_CHARACTERS: ChineseCharacter[] = RAW_CHARACTERS.map((raw, index) => ({
  ...raw,
  lesson: Math.floor(index / CHARS_PER_LESSON) + 1,
}));
